ebook_metadata:
  title: ༄༅། །མཉམ་མེད་སྒམ་པོ་མཆོག་གི་སྤྲུལ་པའི་སྐུས་འཇའ་ཚོན་ཟབ་གཏེར་ཆོག་སྒྲིག་གི་དྲི་རྨེད་གནང་བའི་ལན་དུ་གསོལ་བ་སྙིམ་པའི་ཆུ་སྐྱེས་ཞེས་བྱ་བ་བཞུགས་སོ།
    །
  authors:
  - མཛད་པ་པོ། མཁས་གྲུབ་ཆེན་པོ་རྩེ་ལེ་སྣ་ཚོགས་རང་གྲོལ།
  sku: TSD-TSE-06
  layers:
  - book_title
  - author
  - chapter_title
  - quotation
  - yigchung
web_metadata:
  title:
    en: A Bouquet of Water Lilies:A Respnose to the Peerless Tulku of Gampopa Regarding
      ?
    bo: མཉམ་མེད་སྒམ་པོ་མཆོག་གི་སྤྲུལ་པའི་སྐུས་འཇའ་ཚོན་ཟབ་གཏེར་ཆོག་སྒྲིག་གི་དྲི་རྨེད་གནང་བའི་ལན་དུ་གསོལ་བ་སྙིམ་པའི་ཆུ་སྐྱེས་ཞེས་བྱ་བ་བཞུགས་སོ།
  collection:
    en: Tsele Natsok Rangdrol Series–  Book 6
    bo: རྩེ་ལེ་སྣ་ཚོགས་རང་གྲོལ།–  དེབ། ༦
  author:
    en: Tsele Natsok Rangdrol
    bo: རྩེ་ལེ་སྣ་ཚོགས་རང་གྲོལ།
  pusblisher:
    en: Tsadra Foundation Publishing
    bo: ཙཱ་འདྲ་ཐེབས་རྩ་ཚོགས་པ།
  sku: TSD-TSE-06
  category:
    en: Pith Instructions
    bo: མན་ངག
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: TSD-TSE-06.epub
  description:
    en: ''
    bo: ''
